# Generated by Django 3.2.16 on 2023-01-23 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("view_document_statistics", "Can view document statistics")
                ]
            },
        ),
    ]
