# Generated by Django 3.2.16 on 2023-03-04 23:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_add_statistics_permission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("view_document_statistics", "Can view document statistics"),
                    (
                        "delete_document_undeletable",
                        "Can delete any document from their service",
                    ),
                ]
            },
        ),
    ]
