version: "3.7"
services:
    postgres:
        image: postgres:11
        restart: on-failure
        environment:
            POSTGRES_USER: atv
            POSTGRES_PASSWORD: atv
            POSTGRES_DB: atv
        ports:
            - "5437:5432"
        volumes:
          - pgdata:/var/lib/postgresql/data
        container_name: atv-db

    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        volumes:
            - elastic-data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        container_name: atv-elastic

    kibana:
        image: docker.elastic.co/kibana/kibana:7.15.2
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://atv-elastic:9200
            ELASTICSEARCH_HOSTS: '["http://atv-elastic:9200"]'
        container_name: atv-kibana

    django:
        build:
            context: .
            target: development
        env_file:
            - docker-compose.env.yaml
        environment:
            DATABASE_URL: postgres://atv:atv@atv-db/atv
            DATABASE_HOST: atv-db
        volumes:
            - .:/app
            - django-media-volume:/var/media/
        ports:
            - "8081:8000"
        depends_on:
            - postgres
        container_name: atv-backend

volumes:
        pgdata:
            driver: local
        elastic-data:
            driver: local
        django-media-volume:

networks:
    default:
        name: helsinki
