[tool.ruff]
target-version = "py311"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "atv.settings"
norecursedirs = [".git", "venv*", "var"]
doctest_optionflags = ["NORMALIZE_WHITESPACE", "IGNORE_EXCEPTION_DETAIL", "ALLOW_UNICODE"]

[tool.coverage.run]
branch = true
omit = ["*migrations*", "*site-packages*", "*venv*", "*tests*"]
