# Generated by Django 5.2.9 on 2026-02-07 06:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit_log", "0002_add_explicit_plural"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuditLogEntry",
        ),
    ]
