# Generated by Django 3.2.6 on 2021-08-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_serviceapikey"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "permissions": [
                    ("can_manage_documents", "Can manage documents"),
                    ("can_view_documents", "Can view documents"),
                    ("can_manage_attachments", "Can manage attachments"),
                    ("can_view_attachments", "Can view attachments"),
                ],
                "verbose_name": "service",
                "verbose_name_plural": "services",
            },
        ),
    ]
