# Generated by Django 3.2.7 on 2021-10-21 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0005_add_new_service_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceapikey",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="User to which the permissions of the API key will be attached to. A service user will be automatically generated.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_api_key",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
