# Generated by Django 3.2.9 on 2022-04-13 14:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_add_statushistory_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="status_timestamp",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="Date and time when document status was last changed. Field is automatically set.",
                null=True,
                verbose_name="status_timestamp",
            ),
        ),
    ]
