# Generated by Django 3.2.9 on 2022-06-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0008_alter_attachment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="human_readable_type",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Document type and translations for end user. It's recommended to use ISO 639-1 language codes as key values.",
                verbose_name="human_readable_type",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="status_display_values",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Status display values/translations. It's recommended to use ISO 639-1 language codes as key values.",
                verbose_name="status_display_values",
            ),
        ),
        migrations.AddField(
            model_name="statushistory",
            name="status_display_values",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Status display values/translations. It's recommended to use ISO 639-1 language codes as key values.",
                verbose_name="status_display_values",
            ),
        ),
    ]
