# Generated by Django 3.2.9 on 2022-06-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_document_human_readable_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="status_display_values",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Status display values/translations. It's recommended to use ISO 639-1 language codes as key values.",
                verbose_name="status_display_values",
            ),
        ),
        migrations.AddField(
            model_name="statushistory",
            name="status_display_values",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Status display values/translations. It's recommended to use ISO 639-1 language codes as key values.",
                verbose_name="status_display_values",
            ),
        ),
    ]
