# Generated by Django 3.2.16 on 2023-05-15 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0010_document_deletable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.JSONField(
                        default=dict,
                        help_text="Title for activity/activity message",
                        verbose_name="title",
                    ),
                ),
                (
                    "message",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Message/description of activity for internal use, or for showing to user",
                    ),
                ),
                (
                    "activity_links",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structure with links related to activity with display text in multiple languages",
                    ),
                ),
                (
                    "show_to_user",
                    models.BooleanField(
                        default=False,
                        help_text="Set whether the activity is shown to end user",
                    ),
                ),
                ("activity_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="documents.statushistory",
                    ),
                ),
            ],
            options={
                "ordering": ["-activity_timestamp"],
            },
        ),
    ]
