# Generated by Django 3.2.16 on 2023-05-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0011_add_activity_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statushistory",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
