# Generated by Django 3.2.16 on 2023-05-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0012_alter_statushistory_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_schema_url",
            field=models.URLField(
                blank=True, help_text="Link to content schema if available", null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="document_language",
            field=models.CharField(
                blank=True,
                help_text="ISO 639-1 Language code of document content if known",
                max_length=5,
                null=True,
            ),
        ),
    ]
