# Generated by Django 3.2.19 on 2023-08-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0013_add_document_language_and_content_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="delete_after",
            field=models.DateField(
                help_text="Date which after the document and related attachments are permanently deleted",
                null=True,
            ),
        ),
    ]
