# Generated by Django 4.2.9 on 2024-01-23 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0008_add_display_names_and_service_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0014_document_delete_after"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="service",
            field=models.ForeignKey(
                help_text="The service which owns this document.",
                on_delete=django.db.models.deletion.PROTECT,
                to="services.service",
                verbose_name="service",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The creator/owner of this document.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
