name: CI
on:
  push:
    branches: [main, release]
  pull_request:
jobs:
  common-ci:
    uses: City-of-Helsinki/atv/.github/workflows/ci-api-template.yml@ci_workflow_OH-136
    with:
      python-version: 3.11
      app-name: atv